### ISSUE TITLE
Graphical issues Analogue Pocket 

### ISSUE THREAD

**Issue by neocvera** [MiSTer-devel/Arcade-Atari-system1_MiSTer#2]
Playing Indy, Marble Madness - noticed some pixelation surrounding characters while in motion.

analogue pocket limited transparent smoke.

![IMG_0210](https://github.com/MiSTer-devel/Arcade-Atari-system1_MiSTer/assets/67931174/fe5a333f-69f4-4fc5-bedc-5fa179363507)

**Comment by sorgelig** [comment]
You have to contact Analogue support.
This is MiSTer repository.
